<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KAhtHuXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kAhtHuX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kAhtHuX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.kAhtHuX.App\\Entity\\ReserverLieu', NULL, 'Cannot autowire service ".service_locator.kAhtHuX": it needs an instance of "App\\Entity\\ReserverLieu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\ReserverLieu',
        ]);
    }
}
