<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RmGOHUvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rmGOHUv' shared service.
     *
     * @return \App\Repository\PlaceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\FavoriteController::removeFavorite()": the $placeRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\PlaceRepository".');
    }
}
