<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DqxPMe_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DqxPMe.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DqxPMe.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'toxicityDetectionService' => ['privates', 'App\\Service\\ToxicityDetectionService', 'getToxicityDetectionServiceService', true],
        ], [
            'toxicityDetectionService' => 'App\\Service\\ToxicityDetectionService',
        ]);
    }
}
