<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4BpvV2pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4BpvV2p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4BpvV2p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.4BpvV2p.App\\Entity\\NotificationsAdmin', NULL, 'Cannot autowire service ".service_locator.4BpvV2p": it needs an instance of "App\\Entity\\NotificationsAdmin" but this type has been excluded in "config/services.yaml".'],
        ], [
            'notification' => 'App\\Entity\\NotificationsAdmin',
        ]);
    }
}
