<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ESMu1JcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eSMu1Jc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eSMu1Jc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'googleService' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
            'personnelRepository' => ['privates', 'App\\Repository\\PersonnelRepository', 'getPersonnelRepositoryService', true],
            'reservation' => ['privates', '.errored..service_locator.eSMu1Jc.App\\Entity\\ReservationPerso', NULL, 'Cannot autowire service ".service_locator.eSMu1Jc": it needs an instance of "App\\Entity\\ReservationPerso" but this type has been excluded in "config/services.yaml".'],
            'twilioSmsService' => ['privates', 'App\\Service\\TwilioSmsService', 'getTwilioSmsServiceService', true],
        ], [
            'entityManager' => '?',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'googleService' => 'App\\Service\\GoogleCalendarService',
            'personnelRepository' => 'App\\Repository\\PersonnelRepository',
            'reservation' => 'App\\Entity\\ReservationPerso',
            'twilioSmsService' => 'App\\Service\\TwilioSmsService',
        ]);
    }
}
