<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C6uUeVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c6uUeV_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c6uUeV_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'pack' => ['privates', '.errored..service_locator.c6uUeV_.App\\Entity\\Pack', NULL, 'Cannot autowire service ".service_locator.c6uUeV_": it needs an instance of "App\\Entity\\Pack" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'pack' => 'App\\Entity\\Pack',
        ]);
    }
}
