<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E280P_SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e280P.s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e280P.s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'googleService' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
            'personnelRepository' => ['privates', 'App\\Repository\\PersonnelRepository', 'getPersonnelRepositoryService', true],
        ], [
            'entityManager' => '?',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'googleService' => 'App\\Service\\GoogleCalendarService',
            'personnelRepository' => 'App\\Repository\\PersonnelRepository',
        ]);
    }
}
