<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FE50NizService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FE50Niz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FE50Niz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favoriteRepo' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'placeRepo' => ['privates', '.errored.iriw65v', NULL, 'Cannot determine controller argument for "App\\Controller\\FavoriteController::addFavorite()": the $placeRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\PlaceRepository".'],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'favoriteRepo' => 'App\\Repository\\FavoriteRepository',
            'placeRepo' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
