<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y1HADPLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y1HADPL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y1HADPL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clock' => ['privates', 'clock', 'getClockService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pack' => ['privates', '.errored..service_locator.Y1HADPL.App\\Entity\\Pack', NULL, 'Cannot autowire service ".service_locator.Y1HADPL": it needs an instance of "App\\Entity\\Pack" but this type has been excluded in "config/services.yaml".'],
        ], [
            'clock' => '?',
            'entityManager' => '?',
            'pack' => 'App\\Entity\\Pack',
        ]);
    }
}
