<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KwEU1zJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kwEU1zJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kwEU1zJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notificationsAdminRepository' => ['privates', 'App\\Repository\\NotificationsAdminRepository', 'getNotificationsAdminRepositoryService', true],
        ], [
            'notificationsAdminRepository' => 'App\\Repository\\NotificationsAdminRepository',
        ]);
    }
}
