<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8W7MdrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8_w7Mdr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8_w7Mdr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieu' => ['privates', '.errored..service_locator.8_w7Mdr.App\\Entity\\Lieu', NULL, 'Cannot autowire service ".service_locator.8_w7Mdr": it needs an instance of "App\\Entity\\Lieu" but this type has been excluded in "config/services.yaml".'],
            'reserverLieuRepository' => ['privates', 'App\\Repository\\ReserverLieuRepository', 'getReserverLieuRepositoryService', true],
        ], [
            'lieu' => 'App\\Entity\\Lieu',
            'reserverLieuRepository' => 'App\\Repository\\ReserverLieuRepository',
        ]);
    }
}
