<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZQGcgDRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZQGcgDR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZQGcgDR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieu' => ['privates', '.errored..service_locator.ZQGcgDR.App\\Entity\\Lieu', NULL, 'Cannot autowire service ".service_locator.ZQGcgDR": it needs an instance of "App\\Entity\\Lieu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lieu' => 'App\\Entity\\Lieu',
        ]);
    }
}
