<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailServicePService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailServiceP' shared autowired service.
     *
     * @return \App\Service\EmailServiceP
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmailServiceP.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\EmailServiceP'])) {
            return $container->privates['App\\Service\\EmailServiceP'];
        }

        return $container->privates['App\\Service\\EmailServiceP'] = new \App\Service\EmailServiceP($a, 'service.goldentouch1@gmail.com');
    }
}
