<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dANsewa.App\Entity\Event' shared service.
     *
     * @return \App\Entity\Event
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dANsewa": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".');
    }
}
