<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleCalendarServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GoogleCalendarService' shared autowired service.
     *
     * @return \App\Service\GoogleCalendarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GoogleCalendarService.php';

        return $container->privates['App\\Service\\GoogleCalendarService'] = new \App\Service\GoogleCalendarService($container->getEnv('GOOGLE_CLIENT_ID'), $container->getEnv('GOOGLE_CLIENT_SECRET'), $container->getEnv('GOOGLE_REDIRECT_URI'), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
