<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8_w7Mdr.App\Entity\Lieu' shared service.
     *
     * @return \App\Entity\Lieu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8_w7Mdr": it needs an instance of "App\\Entity\\Lieu" but this type has been excluded in "config/services.yaml".');
    }
}
