<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GNmxONK.App\Entity\Materielle' shared service.
     *
     * @return \App\Entity\Materielle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GNmxONK": it needs an instance of "App\\Entity\\Materielle" but this type has been excluded in "config/services.yaml".');
    }
}
