<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationsAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4BpvV2p.App\Entity\NotificationsAdmin' shared service.
     *
     * @return \App\Entity\NotificationsAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4BpvV2p": it needs an instance of "App\\Entity\\NotificationsAdmin" but this type has been excluded in "config/services.yaml".');
    }
}
