<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MVqKyzB.App\Entity\Personnel' shared service.
     *
     * @return \App\Entity\Personnel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MVqKyzB": it needs an instance of "App\\Entity\\Personnel" but this type has been excluded in "config/services.yaml".');
    }
}
