<?php

namespace ContainerUdtWEHX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationLieu2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.H8mRz8O.App\Entity\ReservationLieu' shared service.
     *
     * @return \App\Entity\ReservationLieu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.H8mRz8O": it needs an instance of "App\\Entity\\ReservationLieu" but this type has been excluded in "config/services.yaml".');
    }
}
