<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'createdEvents' => [parent::class, 'createdEvents', null, 16],
        "\0".parent::class."\0".'dateJoined' => [parent::class, 'dateJoined', null, 16],
        "\0".parent::class."\0".'demandePacks' => [parent::class, 'demandePacks', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'hash' => [parent::class, 'hash', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageData' => [parent::class, 'imageData', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'notificationsAdmins' => [parent::class, 'notificationsAdmins', null, 16],
        "\0".parent::class."\0".'num_tel' => [parent::class, 'num_tel', null, 16],
        "\0".parent::class."\0".'packs' => [parent::class, 'packs', null, 16],
        "\0".parent::class."\0".'paniers' => [parent::class, 'paniers', null, 16],
        "\0".parent::class."\0".'participatedEvents' => [parent::class, 'participatedEvents', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'personnels' => [parent::class, 'personnels', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'reset_token' => [parent::class, 'reset_token', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'salt' => [parent::class, 'salt', null, 16],
        "\0".parent::class."\0".'tokenExpiry' => [parent::class, 'tokenExpiry', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'avis' => [parent::class, 'avis', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'createdEvents' => [parent::class, 'createdEvents', null, 16],
        'dateJoined' => [parent::class, 'dateJoined', null, 16],
        'demandePacks' => [parent::class, 'demandePacks', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'hash' => [parent::class, 'hash', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageData' => [parent::class, 'imageData', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'notificationsAdmins' => [parent::class, 'notificationsAdmins', null, 16],
        'num_tel' => [parent::class, 'num_tel', null, 16],
        'packs' => [parent::class, 'packs', null, 16],
        'paniers' => [parent::class, 'paniers', null, 16],
        'participatedEvents' => [parent::class, 'participatedEvents', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'personnels' => [parent::class, 'personnels', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'reset_token' => [parent::class, 'reset_token', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'salt' => [parent::class, 'salt', null, 16],
        'tokenExpiry' => [parent::class, 'tokenExpiry', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
