<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Materielle extends \App\Entity\Materielle implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie_mat' => [parent::class, 'categorie_mat', null, 16],
        "\0".parent::class."\0".'description_mat' => [parent::class, 'description_mat', null, 16],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null, 16],
        "\0".parent::class."\0".'id_mat' => [parent::class, 'id_mat', null, 16],
        "\0".parent::class."\0".'nom_mat' => [parent::class, 'nom_mat', null, 16],
        "\0".parent::class."\0".'photo_mat' => [parent::class, 'photo_mat', null, 16],
        "\0".parent::class."\0".'prix_mat' => [parent::class, 'prix_mat', null, 16],
        "\0".parent::class."\0".'quantite_mat' => [parent::class, 'quantite_mat', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
        'categorie_mat' => [parent::class, 'categorie_mat', null, 16],
        'description_mat' => [parent::class, 'description_mat', null, 16],
        'events' => [parent::class, 'events', null, 16],
        'id_mat' => [parent::class, 'id_mat', null, 16],
        'nom_mat' => [parent::class, 'nom_mat', null, 16],
        'photo_mat' => [parent::class, 'photo_mat', null, 16],
        'prix_mat' => [parent::class, 'prix_mat', null, 16],
        'quantite_mat' => [parent::class, 'quantite_mat', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
