<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'demandePacks' => [parent::class, 'demandePacks', null, 16],
        "\0".parent::class."\0".'detailPayments' => [parent::class, 'detailPayments', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'pack' => [parent::class, 'pack', null, 16],
        "\0".parent::class."\0".'pack2s' => [parent::class, 'pack2s', null, 16],
        "\0".parent::class."\0".'paniers' => [parent::class, 'paniers', null, 16],
        "\0".parent::class."\0".'payments' => [parent::class, 'payments', null, 16],
        "\0".parent::class."\0".'personnels' => [parent::class, 'personnels', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'reservationsLieu' => [parent::class, 'reservationsLieu', null, 16],
        "\0".parent::class."\0".'reservationsMaterielles' => [parent::class, 'reservationsMaterielles', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        "\0".parent::class."\0".'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'demandePacks' => [parent::class, 'demandePacks', null, 16],
        'detailPayments' => [parent::class, 'detailPayments', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'pack' => [parent::class, 'pack', null, 16],
        'pack2s' => [parent::class, 'pack2s', null, 16],
        'paniers' => [parent::class, 'paniers', null, 16],
        'payments' => [parent::class, 'payments', null, 16],
        'personnels' => [parent::class, 'personnels', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'reservationsLieu' => [parent::class, 'reservationsLieu', null, 16],
        'reservationsMaterielles' => [parent::class, 'reservationsMaterielles', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'utilisateurs' => [parent::class, 'utilisateurs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
