<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pack extends \App\Entity\Pack implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adminId' => [parent::class, 'adminId', null, 16],
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null, 16],
        "\0".parent::class."\0".'capacite' => [parent::class, 'capacite', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null, 16],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null, 16],
        "\0".parent::class."\0".'event' => [parent::class, 'event', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        'adminId' => [parent::class, 'adminId', null, 16],
        'avis' => [parent::class, 'avis', null, 16],
        'capacite' => [parent::class, 'capacite', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'duree' => [parent::class, 'duree', null, 16],
        'endDate' => [parent::class, 'endDate', null, 16],
        'event' => [parent::class, 'event', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
