<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DemandePack extends \App\Entity\DemandePack implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateDemande' => [parent::class, 'dateDemande', null, 16],
        "\0".parent::class."\0".'event' => [parent::class, 'event', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'pack' => [parent::class, 'pack', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        "\0".parent::class."\0".'utilisateurId' => [parent::class, 'utilisateurId', null, 16],
        'dateDemande' => [parent::class, 'dateDemande', null, 16],
        'event' => [parent::class, 'event', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'pack' => [parent::class, 'pack', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'utilisateurId' => [parent::class, 'utilisateurId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
