<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M9v8DVTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M9v8DVT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M9v8DVT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandePackRepository' => ['privates', 'App\\Repository\\DemandePackRepository', 'getDemandePackRepositoryService', true],
            'knpSnappyPdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'demandePackRepository' => 'App\\Repository\\DemandePackRepository',
            'knpSnappyPdf' => '?',
        ]);
    }
}
