<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H8mRz8OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H8mRz8O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H8mRz8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.H8mRz8O.App\\Entity\\ReservationLieu', NULL, 'Cannot autowire service ".service_locator.H8mRz8O": it needs an instance of "App\\Entity\\ReservationLieu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\ReservationLieu',
        ]);
    }
}
