<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KNt9swfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.KNt9swf' shared service.
     *
     * @return \App\Controller\NotificationsAdminRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PackController::listDemandePacks()": the $notificationsRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\NotificationsAdminRepository". Did you forget to add a use statement?');
    }
}
