<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FEh_NOoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FEh.nOo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FEh.nOo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservation' => ['privates', '.errored..service_locator.FEh.nOo.App\\Entity\\ReservationLieu', NULL, 'Cannot autowire service ".service_locator.FEh.nOo": it needs an instance of "App\\Entity\\ReservationLieu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reservation' => 'App\\Entity\\ReservationLieu',
        ]);
    }
}
