<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtdXWO0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VtdXWO0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VtdXWO0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notificationsRepo' => ['privates', '.errored.KNt9swf', NULL, 'Cannot determine controller argument for "App\\Controller\\PackController::listDemandePacks()": the $notificationsRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\NotificationsAdminRepository". Did you forget to add a use statement?'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'notificationsRepo' => '?',
            'paginator' => '?',
        ]);
    }
}
