<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D6g6weNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D6g6weN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D6g6weN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'materielleRepository' => ['privates', 'App\\Repository\\MaterielleRepository', 'getMaterielleRepositoryService', true],
        ], [
            'entityManager' => '?',
            'materielleRepository' => 'App\\Repository\\MaterielleRepository',
        ]);
    }
}
