<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5hgkFgAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5hgkFgA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5hgkFgA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'event' => ['privates', '.errored..service_locator.5hgkFgA.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.5hgkFgA": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'em' => '?',
            'event' => 'App\\Entity\\Event',
            'eventRepository' => 'App\\Repository\\EventRepository',
        ]);
    }
}
