<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MVqKyzBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MVqKyzB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MVqKyzB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'personnel' => ['privates', '.errored..service_locator.MVqKyzB.App\\Entity\\Personnel', NULL, 'Cannot autowire service ".service_locator.MVqKyzB": it needs an instance of "App\\Entity\\Personnel" but this type has been excluded in "config/services.yaml".'],
            'personnelRepository' => ['privates', 'App\\Repository\\PersonnelRepository', 'getPersonnelRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'personnel' => 'App\\Entity\\Personnel',
            'personnelRepository' => 'App\\Repository\\PersonnelRepository',
            'slugger' => '?',
        ]);
    }
}
