<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LDEAEgKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.lDEAEgK' shared service.
     *
     * @return \App\Service\ReviewSentimentService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AvisController::add()": the $reviewSentimentService argument is type-hinted with the non-existent class or interface: "App\\Service\\ReviewSentimentService".');
    }
}
