<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7eXV3udService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7eXV3ud' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7eXV3ud'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reviewSentimentService' => ['privates', '.errored.lDEAEgK', NULL, 'Cannot determine controller argument for "App\\Controller\\AvisController::add()": the $reviewSentimentService argument is type-hinted with the non-existent class or interface: "App\\Service\\ReviewSentimentService".'],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'reviewSentimentService' => '?',
            'validator' => '?',
        ]);
    }
}
