<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomizePackControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\CustomizePackController' shared autowired service.
     *
     * @return \App\Controller\Admin\CustomizePackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'CustomizePackController.php';

        $container->services['App\\Controller\\Admin\\CustomizePackController'] = $instance = new \App\Controller\Admin\CustomizePackController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PackRepository'] ?? $container->load('getPackRepositoryService')), ($container->privates['App\\Repository\\DemandePackRepository'] ?? $container->load('getDemandePackRepositoryService')), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\MaterielleRepository'] ?? $container->load('getMaterielleRepositoryService')), ($container->privates['App\\Repository\\PersonnelRepository'] ?? $container->load('getPersonnelRepositoryService')), ($container->privates['App\\Repository\\LieuRepository'] ?? $container->load('getLieuRepositoryService')), ($container->privates['App\\Repository\\UtilisateurRepository'] ?? $container->load('getUtilisateurRepositoryService')), ($container->privates['App\\Repository\\NotificationsAdminRepository'] ?? $container->load('getNotificationsAdminRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Admin\\CustomizePackController', $container));

        return $instance;
    }
}
