<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPack4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qVxTgn9.App\Entity\Pack' shared service.
     *
     * @return \App\Entity\Pack
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qVxTgn9": it needs an instance of "App\\Entity\\Pack" but this type has been excluded in "config/services.yaml".');
    }
}
