<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationLieuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FEh.nOo.App\Entity\ReservationLieu' shared service.
     *
     * @return \App\Entity\ReservationLieu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FEh.nOo": it needs an instance of "App\\Entity\\ReservationLieu" but this type has been excluded in "config/services.yaml".');
    }
}
