<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationPersoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eSMu1Jc.App\Entity\ReservationPerso' shared service.
     *
     * @return \App\Entity\ReservationPerso
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eSMu1Jc": it needs an instance of "App\\Entity\\ReservationPerso" but this type has been excluded in "config/services.yaml".');
    }
}
