<?php

namespace ContainerXDKZLbb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioSmsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwilioSmsService' shared autowired service.
     *
     * @return \App\Service\TwilioSmsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TwilioSmsService.php';

        return $container->privates['App\\Service\\TwilioSmsService'] = new \App\Service\TwilioSmsService($container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_PHONE_NUMBER'), $container->getEnv('DESTINATION_PHONE_NUMBER'));
    }
}
