controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Add these lines if they don't exist
admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\Admin\DashboardController::index

admin_dashboard_refresh:
    path: /admin/dashboard/refresh
    controller: App\Controller\Admin\DashboardController::refreshDashboardData
    methods: [GET]
