<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9dQwa6K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9dQwa6K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9dQwa6K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9dQwa6K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9dQwa6K\App_KernelDevDebugContainer([
    'container.build_hash' => '9dQwa6K',
    'container.build_id' => 'b15e6c41',
    'container.build_time' => 1745853009,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9dQwa6K');
