<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDEp5Fer\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDEp5Fer/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDEp5Fer.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDEp5Fer\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDEp5Fer\App_KernelDevDebugContainer([
    'container.build_hash' => 'DEp5Fer',
    'container.build_id' => 'cbdb2ab8',
    'container.build_time' => 1745526261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDEp5Fer');
