<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKfzmpd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKfzmpd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKfzmpd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKfzmpd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAKfzmpd\App_KernelDevDebugContainer([
    'container.build_hash' => 'AKfzmpd',
    'container.build_id' => 'e2d68728',
    'container.build_time' => 1745884917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKfzmpd');
